import { ChestType, ConfigSeasonQuest } from '../types';

export type SystemChallenge = ConfigSeasonQuest & {
  source: 'system';
  rewardChest: ChestType;
};

export const SYSTEM_CHALLENGE_INSIGNIA_ID = 'insignia_quest_incomum';

export const SYSTEM_CHALLENGES: SystemChallenge[] = [
  {
    id: 'tutorial-quest',
    source: 'system',
    title: 'Concluir o Tutorial',
    description: 'Feche a trilha inicial do sistema. Recompensa: 1 Bau Comum.',
    type: 'individual',
    category: 'intellectual',
    actionTemplate: {
      name: 'Tutorial de Iniciacao',
      description: 'Concluir a sequencia inicial.',
      icon: '\u{1F393}',
      duration: 0,
      repetitions: 1,
      isMilestone: true,
    },
    requirements: { totalReps: 1, milestone: true },
    rewards: { xp: 1000 },
    rewardChest: 'Comum',
  },
  {
    id: 'system-seven-day-proof-streak',
    source: 'system',
    title: 'Sete Dias em Movimento',
    description: 'Registre pelo menos uma ação real por sete dias seguidos. Recompensa: 1 Baú Incomum.',
    type: 'individual',
    category: 'spiritual',
    actionTemplate: {
      name: 'Sete Dias em Movimento',
      description: 'Manter sete dias seguidos com ao menos uma ação concluída.',
      icon: '\u{1F525}',
      duration: 0,
      repetitions: 7,
      isMilestone: true,
    },
    requirements: { totalReps: 7, milestone: true },
    rewards: { xp: 2000 },
    rewardChest: 'Incomum',
  },
  {
    id: 'system-first-cycle',
    source: 'system',
    title: 'Criar o Primeiro Ciclo',
    description: 'Abra seu primeiro ciclo real. Recompensa: 1 Bau Comum.',
    type: 'individual',
    category: 'intellectual',
    actionTemplate: {
      name: 'Primeiro Ciclo Criado',
      description: 'Ter um ciclo ativo ou um ciclo ja fechado.',
      icon: '\u{1F504}',
      duration: 0,
      repetitions: 1,
      isMilestone: true,
    },
    requirements: { totalReps: 1, milestone: true },
    rewards: { xp: 1500 },
    rewardChest: 'Comum',
  },
  {
    id: 'system-first-campaign',
    source: 'system',
    title: 'Instalar a Primeira Campanha',
    description: 'Instale uma campanha e coloque o sistema para rodar. Recompensa: 1 Bau Comum.',
    type: 'individual',
    category: 'intellectual',
    actionTemplate: {
      name: 'Primeira Campanha Instalada',
      description: 'Ter ao menos uma campanha instalada.',
      icon: '\u{1F4E6}',
      duration: 0,
      repetitions: 1,
      isMilestone: true,
    },
    requirements: { totalReps: 1, milestone: true },
    rewards: { xp: 1250 },
    rewardChest: 'Comum',
  },
  {
    id: 'system-first-arena-clear',
    source: 'system',
    title: 'Completar 3 Arenas',
    description: 'Leve tres arenas diferentes a 100% de progresso. Recompensa: 1 Bau Incomum.',
    type: 'individual',
    category: 'physical',
    actionTemplate: {
      name: 'Tres Arenas Completas',
      description: 'Levar tres arenas diferentes a 100% de progresso.',
      icon: '\u{1F3DF}\uFE0F',
      duration: 0,
      repetitions: 3,
      isMilestone: true,
    },
    requirements: { totalReps: 3, milestone: true },
    rewards: { xp: 2250 },
    rewardChest: 'Incomum',
  },
  {
    id: 'system-first-cycle-report',
    source: 'system',
    title: 'Concluir o Primeiro Ciclo',
    description: 'Feche um ciclo inteiro e gere o primeiro relatorio. Recompensa: 1 Bau Ciclo.',
    type: 'individual',
    category: 'spiritual',
    actionTemplate: {
      name: 'Primeiro Relatorio de Ciclo',
      description: 'Gerar o primeiro relatorio de ciclo completo.',
      icon: '\u{1F4DC}',
      duration: 0,
      repetitions: 1,
      isMilestone: true,
    },
    requirements: { totalReps: 1, milestone: true },
    rewards: { xp: 3500 },
    rewardChest: 'Ciclo',
  },
];
