import { TutorialStep } from '../types';

export const TUTORIAL_SECTIONS = [
    {
        id: 1,
        name: 'Alicerce',
        subtitle: 'Arenas e campanhas do core',
        flag: 'tutorial_level_1_completed',
        badge: 'BRONZE',
        accent: 'from-[#c98a62] via-[#c98a62]/24 via-70% to-transparent',
        glow: 'rgba(197,138,99,0.12)',
        startIndex: 1,
        endIndex: 2,
        gameOnly: false,
    },
    {
        id: 2,
        name: 'Operação',
        subtitle: 'Planner, ciclo e SITREP',
        flag: 'tutorial_level_2_completed',
        badge: 'PRATA',
        accent: 'from-[#9fb4c8] via-[#9fb4c8]/22 via-70% to-transparent',
        glow: 'rgba(166,181,199,0.12)',
        startIndex: 3,
        endIndex: 5,
        gameOnly: false,
    },
    {
        id: 3,
        name: 'Modo Jogo: Progresso',
        subtitle: 'Patentes, maestria e perfil',
        flag: 'tutorial_level_3_completed',
        badge: 'OURO',
        accent: 'from-[#e4bc57] via-[#e4bc57]/24 via-70% to-transparent',
        glow: 'rgba(240,215,135,0.12)',
        startIndex: 6,
        endIndex: 9,
        gameOnly: true,
    },
    {
        id: 4,
        name: 'Modo Jogo: Mundo',
        subtitle: 'Grupos, vínculos e operação compartilhada',
        flag: 'tutorial_level_4_completed',
        badge: 'PREMIUM',
        accent: 'from-[#9b7af2] via-[#9b7af2]/24 via-70% to-transparent',
        glow: 'rgba(179,140,255,0.12)',
        startIndex: 10,
        endIndex: 16,
        gameOnly: true,
    },
] as const;

export const TUTORIAL_STEPS: TutorialStep[] = [
    {
        category: 'INTRO',
        title: 'BEM-VINDO AO GLYPH',
        text: 'Eu sou o Oráculo. Estes 4 cards explicam o sistema no seu ritmo.\n\nOs cards 1 e 2 cobrem o core. Quando quiser a camada extra, o Modo Jogo libera os cards 3 e 4.',
        view: 'arenas',
        targetId: 'nav-arenas',
    },

    {
        category: 'ALICERCE',
        title: '01. ARENAS',
        text: 'Aqui você organiza as frentes da sua vida. Este card mostra a estrutura geral das Arenas, sem exigir que você monte tudo de uma vez.',
        view: 'arenas',
        targetId: 'arenas-container',
    },
    {
        category: 'ALICERCE',
        title: '02. CAMPANHAS',
        text: 'Quando uma meta for maior, campanhas viram um corredor de fases dentro das suas Arenas. Elas ajudam a manter clareza sem te afogar em complexidade.',
        view: 'arenas',
        targetId: 'campaigns-section',
    },
    {
        category: 'ALICERCE',
        title: '03. PLANNER',
        text: 'O Planner puxa suas ações para a semana e para o dia. É aqui que a intenção vira campo de batalha.',
        view: 'planner',
        targetId: 'planner-container',
    },
    {
        category: 'ALICERCE',
        title: '04. CICLO',
        text: 'O ciclo é o ritmo que segura a jornada. Ele te ajuda a ver onde você está, o que vem agora e quando revisar a fase.',
        view: 'planner',
        targetId: 'cycle-hud',
    },
    {
        category: 'ALICERCE',
        title: '05. SITREP',
        text: 'O SITREP acompanha o dia, alinha foco e evita atrito. Se você entender Arena, Planner, Ciclo e SITREP, o núcleo do GLYPH já está na sua mão.',
        view: 'planner',
        targetId: 'sitrep-button',
    },

    {
        category: 'IDENTIDADE',
        title: '06. PATENTES',
        text: 'O segundo card fala de progresso visível. Patentes mostram sua escalada dentro do sistema e ajudam a sentir que a jornada está andando.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'profile-section',
    },
    {
        category: 'IDENTIDADE',
        title: '07. MAESTRIA',
        text: 'Aqui você enxerga como está distribuindo força nas áreas da vida. O decágono e os sliders deixam sua calibragem clara de um jeito rápido.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'mastery-sliders-button',
    },
    {
        category: 'IDENTIDADE',
        title: '08. PERFIL SOBERANO',
        text: 'O perfil junta identidade, leitura visual e vitrine. Ele mostra quem você está se tornando dentro do GLYPH.',
        view: 'assets',
        showProfile: true,
        targetId: 'shareable-profile',
    },
    {
        category: 'IDENTIDADE',
        title: '09. PREFERENCIAS',
        text: 'Aqui você ajusta o tom da experiência. O core segue igual; o Modo Jogo liga jornadas de temporada, patentes, baús, inventário, Hall da Fama e soberano.',
        view: 'settings',
        tab: 'Preferências',
        targetId: 'mode-game-toggle',
    },

    {
        category: 'MUNDO',
        title: '10. GRUPOS',
        text: 'Aqui o sistema deixa de ser só seu. Grupos abrem uma camada compartilhada de presença, jornadas e organização, sem tirar o foco do seu app pessoal.',
        view: 'social',
        targetId: 'nav-mundo',
    },
    {
        category: 'MUNDO',
        title: '11. VÍNCULOS',
        text: 'Vínculos abrem mentoria, parceria e acompanhamento. Aqui você pode compartilhar arenas, campanhas e direção com outra pessoa sem sair do sistema.',
        view: 'social',
        targetId: 'links-button',
    },
    {
        category: 'MUNDO',
        title: '12. ORÁCULO E AÇÃO',
        text: 'O Oráculo lê o contexto da sua jornada. E, quando você quiser operar o sistema, a aba Ação entra para transformar intenção em estrutura e execução.',
        view: 'assets',
        targetId: 'header-oracle',
    },

    {
        category: 'ARQUITETO',
        title: '13. BIBLIOTECA',
        text: 'Aqui ficam campanhas autorais, códices e estruturas reutilizáveis. É onde método pronto vira material que você pode instalar, adaptar e compartilhar.',
        view: 'social',
        tab: 'arsenal',
        targetId: 'arsenal-library-button',
    },
    {
        category: 'ARQUITETO',
        title: '14. CAMPANHAS',
        text: 'Campanhas juntam fases, ações e progresso em jornadas longas. É assim que cursos, projetos grandes e trilhas guiadas ficam legíveis sem virar caos.',
        view: 'arenas',
        targetId: 'campaigns-button',
    },
    {
        category: 'ARQUITETO',
        title: '15. PREFERÊNCIAS DO ORÁCULO',
        text: 'Aqui você regula a camada de IA: modo, categorias, notificações e o quanto o Oráculo participa da operação do seu sistema.',
        view: 'settings',
        tab: 'Preferências',
        targetId: 'oracle-preferences-setting',
    },
    {
        category: 'ARQUITETO',
        title: 'TUTORIAL CONCLUÍDO',
        text: 'Para começar bem, lembre só do essencial: Arena, Planner, Ciclo e SITREP.\n\nOs cards 1 e 2 cobrem o core. Em Configurações > Preferências, você ativa o Modo Jogo para liberar também os cards 3 e 4.',
        view: 'planner',
        targetId: 'sitrep-button',
    },
];

