import { TutorialStep } from '../types';

export const TUTORIAL_STEPS: TutorialStep[] = [
    {
        category: 'INTRO',
        title: 'BEM-VINDO AO GLYPH',
        text: 'Eu sou o Oraculo. Estes 4 cards explicam o sistema no seu ritmo.\n\nO primeiro funciona como uma visao geral do core loop para revisitar depois do onboarding.',
        view: 'arenas',
        targetId: 'nav-arenas',
    },

    {
        category: 'ALICERCE',
        title: '01. ARENAS',
        text: 'Aqui voce organiza as frentes da sua vida. Este card mostra a estrutura geral das Arenas, sem exigir que voce monte tudo de uma vez.',
        view: 'arenas',
        targetId: 'arenas-container',
    },
    {
        category: 'ALICERCE',
        title: '02. CAMPANHAS',
        text: 'Quando uma meta for maior, campanhas viram um corredor de fases dentro das suas Arenas. Elas ajudam a manter clareza sem te afogar em complexidade.',
        view: 'arenas',
        targetId: 'campaigns-section',
    },
    {
        category: 'ALICERCE',
        title: '03. PLANNER',
        text: 'O Planner puxa suas acoes para a semana e para o dia. E aqui que a intencao vira campo de batalha.',
        view: 'planner',
        targetId: 'planner-container',
    },
    {
        category: 'ALICERCE',
        title: '04. CICLO',
        text: 'O ciclo e o ritmo que segura a jornada. Ele te ajuda a ver onde voce esta, o que vem agora e quando revisar a fase.',
        view: 'planner',
        targetId: 'cycle-hud',
    },
    {
        category: 'ALICERCE',
        title: '05. SITREP',
        text: 'O SITREP acompanha o dia, alinha foco e evita atrito. Se voce entender Arena, Planner, Ciclo e SITREP, o nucleo do GLYPH ja esta na sua mao.',
        view: 'planner',
        targetId: 'sitrep-button',
    },

    {
        category: 'IDENTIDADE',
        title: '06. PATENTES',
        text: 'O segundo card fala de progresso visivel. Patentes mostram sua escalada dentro do sistema e ajudam a sentir que a jornada esta andando.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'profile-section',
    },
    {
        category: 'IDENTIDADE',
        title: '07. MAESTRIA',
        text: 'Aqui voce enxerga como esta distribuindo forca nas areas da vida. O decagono e os sliders deixam sua calibragem clara de um jeito rapido.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'mastery-sliders-button',
    },
    {
        category: 'IDENTIDADE',
        title: '08. PERFIL SOBERANO',
        text: 'O perfil junta identidade, leitura visual e vitrine. Ele mostra quem voce esta se tornando dentro do GLYPH.',
        view: 'assets',
        showProfile: true,
        targetId: 'shareable-profile',
    },
    {
        category: 'IDENTIDADE',
        title: '09. PREFERENCIAS',
        text: 'Aqui voce ajusta o tom da experiencia. O sistema pode ficar mais limpo, mais game ou mais assistido, do jeito que fizer sentido para voce.',
        view: 'settings',
        tab: 'Preferências',
        targetId: 'nav-settings',
    },

    {
        category: 'MUNDO',
        title: '10. MUNDO SOCIAL',
        text: 'No terceiro card o sistema deixa de ser so seu. Entram aliados, clãs, quests e outras camadas de mundo.',
        view: 'social',
        targetId: 'nav-mundo',
    },
    {
        category: 'MUNDO',
        title: '11. VINCULOS',
        text: 'Vinculos abrem mentoria, parceria e observacao. Agora um mentor tambem pode passar um Codex autoral para o pupilo ou criar um na hora para ele.',
        view: 'settings',
        tab: 'Premium',
        targetId: 'links-button',
    },
    {
        category: 'MUNDO',
        title: '12. ORACULO',
        text: 'O Oraculo e a camada de leitura do sistema. Ele acompanha a jornada, interpreta contexto e pode te ajudar a decidir melhor.',
        view: 'assets',
        targetId: 'header-oracle',
    },

    {
        category: 'ARQUITETO',
        title: '13. CODEX',
        text: 'No quarto card voce para de so usar estrutura e comeca a criar estrutura. Codex transforma metodo em campanha reutilizavel.',
        view: 'settings',
        tab: 'Premium',
        targetId: 'codex-button',
    },
    {
        category: 'ARQUITETO',
        title: '14. CAMPANHAS MAIORES',
        text: 'Campanhas juntam fases, arenas e progresso em jornadas longas. E assim que projetos grandes ficam legiveis sem virar caos.',
        view: 'settings',
        tab: 'Premium',
        targetId: 'campaigns-button',
    },
    {
        category: 'ARQUITETO',
        title: '15. IA E OPERACAO',
        text: 'Aqui entram as camadas mais avancadas: assistente, estruturas de operacao e recursos para escalar o sistema junto com voce.',
        view: 'settings',
        tab: 'Premium',
        targetId: 'assistant-button',
    },
    {
        category: 'ARQUITETO',
        title: 'TUTORIAL CONCLUIDO',
        text: 'Para comecar bem, lembre so do essencial: Arena, Planner, Ciclo e SITREP.\n\nO resto existe para expandir quando sua base ja estiver firme.',
        view: 'planner',
        targetId: 'sitrep-button',
    },
];

