import { TutorialStep } from '../types';

export const TUTORIAL_SECTIONS = [
    {
        id: 1,
        name: 'Alicerce',
        subtitle: 'Arenas e campanhas do core',
        flag: 'tutorial_level_1_completed',
        badge: 'BRONZE',
        accent: 'from-[#c98a62] via-[#c98a62]/24 via-70% to-transparent',
        glow: 'rgba(197,138,99,0.12)',
        startIndex: 1,
        endIndex: 2,
        gameOnly: false,
    },
    {
        id: 2,
        name: 'Operacao',
        subtitle: 'Planner, ciclo e SITREP',
        flag: 'tutorial_level_2_completed',
        badge: 'PRATA',
        accent: 'from-[#9fb4c8] via-[#9fb4c8]/22 via-70% to-transparent',
        glow: 'rgba(166,181,199,0.12)',
        startIndex: 3,
        endIndex: 5,
        gameOnly: false,
    },
    {
        id: 3,
        name: 'Modo Jogo: Progresso',
        subtitle: 'Patentes, maestria e perfil',
        flag: 'tutorial_level_3_completed',
        badge: 'OURO',
        accent: 'from-[#e4bc57] via-[#e4bc57]/24 via-70% to-transparent',
        glow: 'rgba(240,215,135,0.12)',
        startIndex: 6,
        endIndex: 9,
        gameOnly: true,
    },
    {
        id: 4,
        name: 'Modo Jogo: Mundo',
        subtitle: 'Grupos, vinculos e metajogo',
        flag: 'tutorial_level_4_completed',
        badge: 'PREMIUM',
        accent: 'from-[#9b7af2] via-[#9b7af2]/24 via-70% to-transparent',
        glow: 'rgba(179,140,255,0.12)',
        startIndex: 10,
        endIndex: 16,
        gameOnly: true,
    },
] as const;

export const TUTORIAL_STEPS: TutorialStep[] = [
    {
        category: 'INTRO',
        title: 'BEM-VINDO AO GLYPH',
        text: 'Eu sou o Oraculo. Estes 4 cards explicam o sistema no seu ritmo.\n\nOs cards 1 e 2 cobrem o core. Quando quiser a camada extra, o Modo Jogo libera os cards 3 e 4.',
        view: 'arenas',
        targetId: 'nav-arenas',
    },

    {
        category: 'ALICERCE',
        title: '01. ARENAS',
        text: 'Aqui voce organiza as frentes da sua vida. Este card mostra a estrutura geral das Arenas, sem exigir que voce monte tudo de uma vez.',
        view: 'arenas',
        targetId: 'arenas-container',
    },
    {
        category: 'ALICERCE',
        title: '02. CAMPANHAS',
        text: 'Quando uma meta for maior, campanhas viram um corredor de fases dentro das suas Arenas. Elas ajudam a manter clareza sem te afogar em complexidade.',
        view: 'arenas',
        targetId: 'campaigns-section',
    },
    {
        category: 'ALICERCE',
        title: '03. PLANNER',
        text: 'O Planner puxa suas acoes para a semana e para o dia. E aqui que a intencao vira campo de batalha.',
        view: 'planner',
        targetId: 'planner-container',
    },
    {
        category: 'ALICERCE',
        title: '04. CICLO',
        text: 'O ciclo e o ritmo que segura a jornada. Ele te ajuda a ver onde voce esta, o que vem agora e quando revisar a fase.',
        view: 'planner',
        targetId: 'cycle-hud',
    },
    {
        category: 'ALICERCE',
        title: '05. SITREP',
        text: 'O SITREP acompanha o dia, alinha foco e evita atrito. Se voce entender Arena, Planner, Ciclo e SITREP, o nucleo do GLYPH ja esta na sua mao.',
        view: 'planner',
        targetId: 'sitrep-button',
    },

    {
        category: 'IDENTIDADE',
        title: '06. PATENTES',
        text: 'O segundo card fala de progresso visivel. Patentes mostram sua escalada dentro do sistema e ajudam a sentir que a jornada esta andando.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'profile-section',
    },
    {
        category: 'IDENTIDADE',
        title: '07. MAESTRIA',
        text: 'Aqui voce enxerga como esta distribuindo forca nas areas da vida. O decagono e os sliders deixam sua calibragem clara de um jeito rapido.',
        view: 'settings',
        tab: 'Geral',
        targetId: 'mastery-sliders-button',
    },
    {
        category: 'IDENTIDADE',
        title: '08. PERFIL SOBERANO',
        text: 'O perfil junta identidade, leitura visual e vitrine. Ele mostra quem voce esta se tornando dentro do GLYPH.',
        view: 'assets',
        showProfile: true,
        targetId: 'shareable-profile',
    },
    {
        category: 'IDENTIDADE',
        title: '09. PREFERENCIAS',
        text: 'Aqui voce ajusta o tom da experiencia. O core segue igual; o Modo Jogo liga quests, patentes, baus, inventario, Hall da Fama e soberano.',
        view: 'settings',
        tab: 'Preferências',
        targetId: 'mode-game-toggle',
    },

    {
        category: 'MUNDO',
        title: '10. MUNDO SOCIAL',
        text: 'No quarto card o sistema deixa de ser so seu. Aqui entram grupos, vinculos e a camada compartilhada do GLYPH. Com o Modo Jogo ligado, esse mundo tambem ganha quests e outras trilhas de metajogo.',
        view: 'social',
        targetId: 'nav-mundo',
    },
    {
        category: 'MUNDO',
        title: '11. VINCULOS',
        text: 'Vinculos abrem mentoria, parceria e observacao. Agora um mentor tambem pode passar uma campanha autoral para o pupilo ou montar uma na hora para ele.',
        view: 'social',
        targetId: 'links-button',
    },
    {
        category: 'MUNDO',
        title: '12. ORACULO',
        text: 'O Oraculo e a camada de leitura do sistema. Ele acompanha a jornada, interpreta contexto e pode te ajudar a decidir melhor.',
        view: 'assets',
        targetId: 'header-oracle',
    },

    {
        category: 'ARQUITETO',
        title: '13. BIBLIOTECA',
        text: 'Aqui ficam as campanhas autorais e outras estruturas reutilizaveis. E onde metodo pronto vira material vivo para reaplicar, adaptar e compartilhar.',
        view: 'social',
        tab: 'arsenal',
        targetId: 'arsenal-library-button',
    },
    {
        category: 'ARQUITETO',
        title: '14. CAMPANHAS',
        text: 'Campanhas juntam fases, arenas e progresso em jornadas longas. E assim que projetos grandes ficam legiveis sem virar caos.',
        view: 'arenas',
        targetId: 'campaigns-button',
    },
    {
        category: 'ARQUITETO',
        title: '15. ASSISTENTE E IA',
        text: 'Aqui entram as camadas mais avancadas: assistente, estruturas de operacao e recursos para escalar o sistema junto com voce.',
        view: 'settings',
        tab: 'Preferências',
        targetId: 'oracle-preferences-setting',
    },
    {
        category: 'ARQUITETO',
        title: 'TUTORIAL CONCLUIDO',
        text: 'Para comecar bem, lembre so do essencial: Arena, Planner, Ciclo e SITREP.\n\nOs cards 1 e 2 cobrem o core. Em Configuracoes > Preferencias, voce ativa o Modo Jogo para liberar tambem os cards 3 e 4.',
        view: 'planner',
        targetId: 'sitrep-button',
    },
];

