// Dev-only account fixture; no credentials, purchases or real database writes.
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:430,height:1040}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto('http://localhost:3018/zen3d-test/account-check.html');
  let garden=page.frameLocator('#garden');
  await garden.getByRole('button',{name:'Salvar',exact:true}).waitFor();
  await garden.locator('canvas').waitFor();
  await garden.getByRole('button',{name:'Itens',exact:true}).click();
  assert.deepEqual(await garden.getByRole('combobox',{name:'Filtrar coleção'}).locator('option').allTextContents(),['Todas as coleções','Refúgio natural','Pátio dourado']);
  await garden.getByRole('button',{name:'Artefatos',exact:true}).click();
  assert.equal(await garden.locator('.inventory-card').count(),1);
  assert.match(await garden.locator('.inventory-card').innerText(),/Adaga/i);
  await garden.getByRole('button',{name:'Insígnias',exact:true}).click();
  assert.equal(await garden.locator('.inventory-card').count(),0);
  await garden.getByRole('button',{name:'Pedras',exact:true}).click();
  await garden.getByRole('combobox',{name:'Filtrar coleção'}).selectOption('luxury');
  await garden.getByRole('button',{name:'Seixo de calcário',exact:false}).click();
  await garden.locator('canvas').click({position:{x:212,y:520}});
  await garden.getByRole('button',{name:'Girar',exact:true}).click();
  await garden.getByRole('button',{name:'Loja',exact:true}).click();
  assert.equal(await garden.getByRole('button',{name:'Comprar · 500 ouro',exact:true}).count(),1);
  await garden.getByRole('button',{name:'Modelos de jardim',exact:true}).click();
  assert.equal(await garden.getByRole('button',{name:'Ver modelo',exact:true}).count(),1);
  await garden.getByRole('button',{name:'Areia',exact:true}).click();
  await garden.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#report').textContent.includes('"saves":1'));
  const blank=JSON.parse(await page.locator('#report').innerText());
  const canvas=await garden.locator('canvas').boundingBox();
  await page.mouse.move(canvas.x+190,canvas.y+360);await page.mouse.down();
  for(let i=0;i<18;i++){await page.mouse.move(canvas.x+190+35*Math.sin(i/7),canvas.y+360+i*7);await page.waitForTimeout(20);}
  await page.mouse.up();
  await garden.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#report').textContent.includes('"saves":2'));
  const drawn=JSON.parse(await page.locator('#report').innerText());
  assert.notEqual(drawn.height,blank.height,'Drawing must change the height texture.');
  assert.ok(drawn.bytes<3200000,'Snapshot must fit server limit.');
  assert.equal(drawn.objects,7,'Added rock must be persisted.');
  await page.getByRole('button',{name:'Reabrir salvo',exact:true}).click();
  await garden.getByRole('button',{name:'Salvar',exact:true}).waitFor();
  await garden.locator('canvas').waitFor();
  await garden.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#report').textContent.includes('"saves":3'));
  const restored=JSON.parse(await page.locator('#report').innerText());
  assert.equal(restored.layout,drawn.layout,'Positions, rotations and per-object kits must survive reopening.');
  assert.equal(restored.height,drawn.height,'Height must survive close/reopen exactly.');
  assert.equal(restored.color,drawn.color,'Sand color texture must survive close/reopen exactly.');
  await page.getByRole('button',{name:'Simular falha no próximo salvamento',exact:true}).click();
  await garden.getByRole('button',{name:'Salvar',exact:true}).click();
  await garden.getByRole('status').filter({hasText:'Falha simulada'}).waitFor();
  assert.equal(JSON.parse(await page.locator('#report').innerText()).saves,3);
  assert.equal(await garden.getByRole('button',{name:'Salvar',exact:true}).isEnabled(),true);
  await garden.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#report').textContent.includes('"saves":4'));
  await page.evaluate(()=>{
    window.exitResult=null;
    window.addEventListener('message',e=>{if(e.data?.type==='glyph-garden-save-exit-result')window.exitResult=e.data.ok;});
    document.querySelector('iframe').contentWindow.postMessage({type:'glyph-garden-save-exit'},location.origin);
  });
  await page.waitForFunction(()=>window.exitResult===true);
  assert.equal(JSON.parse(await page.locator('#report').innerText()).saves,5);
  await page.getByRole('button',{name:'Simular falha no próximo salvamento',exact:true}).click();
  await page.evaluate(()=>{window.exitResult=null;document.querySelector('iframe').contentWindow.postMessage({type:'glyph-garden-save-exit'},location.origin);});
  await page.waitForFunction(()=>window.exitResult===false);
  assert.equal(JSON.parse(await page.locator('#report').innerText()).saves,5);
  assert.deepEqual(errors,[]);
  if(process.env.GARDEN_SCREENSHOT)await garden.locator('main').screenshot({path:process.env.GARDEN_SCREENSHOT});
  console.log(`Garden browser: owned inventory, kit/base locks, explicit save, exact sand roundtrip and failure recovery passed (${drawn.bytes} bytes).`);
} finally {await browser.close();}
