import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MetalReportCard,getMetalRankPalette} from '../../components/MetalReportCard';
import '../../index.css';
import './cycle-plate-study.css';
const ranks=['B','SS'];
const stats=[['Ações','50/54'],['Carga','46h'],['Metas','6/9'],['Presença','7 dias']];
function Seal({kind}:{kind:number}){return <svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43" fill="none" stroke="currentColor" strokeWidth="1"/>{kind===1?<><path d="M50 14 77 36 70 73 50 86 30 73 23 36Z M50 25 65 40 62 65 50 74 38 65 35 40Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="m39 49 9 10 17-22" fill="none" stroke="currentColor" strokeWidth="3"/></>:kind===2?<><path d="M28 69Q9 45 31 26M72 69Q91 45 69 26M24 56 14 48M24 43 17 33M76 56 86 48M76 43 83 33" fill="none" stroke="currentColor" strokeWidth="3"/><path d="m50 24 8 19 20 7-20 7-8 19-8-19-20-7 20-7Z" fill="currentColor" opacity=".8"/></>:<><path d="m50 17 12 21 24 12-24 12-12 21-12-21-24-12 24-12Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="m50 32 18 18-18 18-18-18Z" fill="currentColor" opacity=".75"/></>}</svg>}
function Proposal({kind,rank,seal}:{kind:number;rank:string;seal:boolean}){const p=getMetalRankPalette(rank);const max=rank==='SS';return <article className={`proposal p${kind} ${max?'luxury':''}`} style={{'--base':p.base,'--deep':p.baseDeep,'--light':p.highlight,'--edge':p.edge,'--ink':p.text} as React.CSSProperties}>
 <div className="plate-frame"/><header className="plate-top"><span>CICLO 01</span><span>25 MAI — 31 MAI</span></header>
 <div className="plate-hero">{seal&&<div className="concept-seal"><Seal kind={kind}/></div>}<div className="grade">{rank}</div><div className="score"><span>NOTA</span><strong>{max?'100':'83'}</strong><small>/100</small></div></div>
 <div className="plate-name"><span>{max?'REGISTRO EXCEPCIONAL':'JORNADA REGISTRADA'}</span><h3>Ciclo de maio</h3></div>
 <div className="plate-stats">{stats.map(([label,val])=><div key={label}><span>{label}</span><strong>{max?({'Ações':'54/54','Metas':'9/9'}[label]||val):val}</strong></div>)}</div>
 <footer className="plate-foot"><span>ERA I</span><i/><span>{p.label.toUpperCase()}</span></footer>
 </article>}
const ideas=[{name:'Metal gravado',desc:'Nota no eixo, selo como assinatura de canto e informações gravadas em uma base escura.',seal:'Selo 1 · carimbo geométrico'}, {name:'Medalhão',desc:'O patamar vira uma medalha central; no SS, ouro e violeta acentuam o relevo.',seal:'Selo 2 · louros e estrela'}, {name:'Placa cerimonial',desc:'Cantos recortados, linhas arquitetônicas e acabamento de objeto colecionável.',seal:'Selo 3 · marca em losango'}];
function App(){const[seal,setSeal]=useState(true);const normal='B';return <main className="cycle-study"><header className="study-heading"><div><p className="eyebrow">GLYPH / ESTUDO DE FORMA / 01</p><h1>Um ciclo.<br/><em>Três maneiras de guardar.</em></h1><p className="intro">Referência atual + três estilos, só com médio (B) e fodão (SS). Informações e selos são propostas; nada foi aplicado no app.</p></div><aside><span className="legend-label">SÓ DOIS PATAMARES</span><div className="rank-spectrum">{ranks.map(r=><span key={r} style={{color:getMetalRankPalette(r).highlight,borderColor:getMetalRankPalette(r).base}}>{r}</span>)}</div><label className="toggle"><input type="checkbox" checked={seal} onChange={e=>setSeal(e.target.checked)}/> Mostrar selos nas propostas</label><small>Médio (B) e fodão (SS), lado a lado. Dados ilustrativos para comparar o estilo.</small></aside></header>
 <section className="study-row reference"><div className="row-copy"><span className="row-index">00 / REFERÊNCIA</span><h2>Como está hoje</h2><p>O próprio componente do app, sem alterações. Versão grande, não a compacta do histórico.</p><span className="seal-note">Selo atual preservado nesta dupla</span></div><div className="pair">{[normal,'SS'].map(r=><div className="sample" key={r}><div className="sample-label"><span>{r==='SS'?'FODÃO / MÁXIMO':'MÉDIO'}</span><b>{r}</b></div><MetalReportCard rank={r} score={r==='SS'?100:83} title="Ciclo de maio" subtitle="Ciclo consolidado" dateRange="25/05 — 31/05" metrics={stats.map(([label,value])=>({label,value}))} /></div>)}</div></section>
 {ideas.map((idea,i)=><section className="study-row" key={idea.name}><div className="row-copy"><span className="row-index">0{i+1} / PROPOSTA</span><h2>{idea.name}</h2><p>{idea.desc}</p><span className="seal-note">{idea.seal}</span></div><div className="pair">{[normal,'SS'].map(r=><div className="sample" key={r}><div className="sample-label"><span>{r==='SS'?'FODÃO / MÁXIMO':'MÉDIO'}</span><b>{r}</b></div><Proposal kind={i+1} rank={r} seal={seal}/></div>)}</div></section>)}
 <footer className="study-end">Somente estudo visual · os usos do app permanecem intactos · depois da escolha, adaptar grande e compacto juntos.</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);

