import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useThree} from '@react-three/fiber';
import {QualityGardenProvider,QualityGardenObjects,useQualityLibrary} from '../views/zen3d/QualityGardenObjects';
import {GardenLanterns} from '../views/zen3d/GardenLanterns';
import type {GardenObject} from '../views/zen3d/model';
import {KITS,type KitId} from '../views/zen3d/kits';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
function Navigation(){const {camera,gl}=useThree();useEffect(()=>{const controls=new OrbitControls(camera,gl.domElement);controls.target.set(0,.5,0);controls.minZoom=35;controls.maxZoom=180;controls.maxPolarAngle=Math.PI*.48;controls.update();return()=>controls.dispose();},[camera,gl]);return null;}
function Sand(){const library=useQualityLibrary();return <mesh rotation={[-Math.PI/2,0,0]} position={[0,-.015,0]} receiveShadow><planeGeometry args={[18,14]}/><meshStandardMaterial map={library?.sand} roughnessMap={library?.rough} color="#ded8c5" roughness={1}/></mesh>;}
const rows=[['strata-stone',-3.5,-.5],['wood-walkway',-.9,0],['fern',1.7,0],['low-lantern',3.7,0]] as const;
function App(){const [kit,setKit]=useState<KitId>('starter'),[night,setNight]=useState(false),[error,setError]=useState('');const objects:GardenObject[]=rows.map(([type,x,z])=>({id:type,type,kit,position:[x,0,z],rotation:0,variant:0}));return <main style={{margin:0,background:'#182124',color:'#eee',fontFamily:'system-ui',minHeight:'100vh'}}><header style={{padding:20}}><h2>Quatro peças · Jardim 3D</h2><p>Laje estratificada · Passarela · Samambaia · Luminária baixa</p>{KITS.map(k=><button key={k.id} aria-pressed={kit===k.id} onClick={()=>setKit(k.id)} style={{padding:12,marginRight:8}}>{k.name}</button>)}<button onClick={()=>setNight(n=>!n)} style={{padding:12}}>{night?'Ver dia':'Ver noite'}</button><p>{error||'Arraste para girar · roda para aproximar · bancada sem conta'}</p></header><div style={{height:'70vh',minHeight:420}}><Canvas shadows orthographic camera={{position:[8,8,12],zoom:65,near:.1,far:100}}><Navigation/><color attach="background" args={[night?'#101925':'#bec9c9']}/><ambientLight intensity={night?.8:1.3}/><directionalLight position={[3,8,4]} intensity={night?.3:3} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-9} shadow-camera-right={9} shadow-camera-top={9} shadow-camera-bottom={-9}/><QualityGardenProvider onError={setError}><Sand/><QualityGardenObjects objects={objects} select={()=>{}}/><QualityGardenObjects objects={[{id:'reference',type:'pine',kit,position:[-4,0,-4],rotation:.4,variant:0}]} select={()=>{}}/></QualityGardenProvider><GardenLanterns objects={objects} night={night?1:0}/></Canvas></div></main>};const root=createRoot(document.getElementById('root')!);root.render(<App/>);if(import.meta.hot)import.meta.hot.dispose(()=>root.unmount());
