-- Fix conflicts by dropping existing functions
DROP FUNCTION IF EXISTS craft_item(integer, text, text);
DROP FUNCTION IF EXISTS recycle_item(text);
DROP FUNCTION IF EXISTS recycle_item(uuid);
DROP FUNCTION IF EXISTS buy_gold_pack(text, integer, numeric);
DROP FUNCTION IF EXISTS buy_store_item(text, integer, text);

-- Ensure dependencies exist
CREATE TABLE IF NOT EXISTS user_inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL,
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_equipped BOOLEAN DEFAULT FALSE,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS user_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  product_type VARCHAR(20) NOT NULL,
  product_id VARCHAR(50) NOT NULL,
  gold_spent INT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT TRUE,
  purchased_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Re-create functions

-- 1. Recycle Item (UUID based)
CREATE OR REPLACE FUNCTION recycle_item(p_item_instance_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_item_id TEXT;
  v_fragments INT;
  v_item_name TEXT;
BEGIN
  v_user_id := auth.uid();
  
  -- Get item info and verify ownership
  SELECT i.id, i.recycle_value, i.name
  INTO v_item_id, v_fragments, v_item_name
  FROM user_inventory u
  JOIN items i ON u.item_id = i.id
  WHERE u.id = p_item_instance_id AND u.user_id = v_user_id;
  
  IF v_item_id IS NULL THEN
    RAISE EXCEPTION 'Item not found or not owned by user';
  END IF;

  -- Delete from inventory
  DELETE FROM user_inventory WHERE id = p_item_instance_id;
  
  -- Update fragments
  UPDATE user_profiles
  SET fragments = COALESCE(fragments, 0) + v_fragments
  WHERE id = v_user_id;
  
  -- Log transaction
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'recycle', 'fragments', v_fragments, 'Recycled ' || v_item_name);
  
  RETURN jsonb_build_object('success', true, 'fragments_gained', v_fragments);
END;
$$;

-- 2. Craft Item
CREATE OR REPLACE FUNCTION craft_item(
  p_tier INT,
  p_category TEXT DEFAULT NULL,
  p_exact_item_id TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_cost INT;
  v_target_item_id TEXT;
  v_fragments_owned INT;
  v_item_name TEXT;
  v_new_instance_id UUID;
BEGIN
  v_user_id := auth.uid();
  
  -- Determine cost
  CASE p_tier
    WHEN 1 THEN v_cost := 40;
    WHEN 2 THEN v_cost := 120;
    WHEN 3 THEN v_cost := 400;
    WHEN 4 THEN v_cost := 1200;
    WHEN 5 THEN v_cost := 4000;
    ELSE RAISE EXCEPTION 'Invalid tier';
  END CASE;
  
  -- Check funds
  SELECT fragments INTO v_fragments_owned FROM user_profiles WHERE id = v_user_id;
  IF v_fragments_owned < v_cost THEN
    RAISE EXCEPTION 'Insufficient fragments';
  END IF;
  
  -- Determine item
  IF p_tier <= 3 THEN
    IF p_exact_item_id IS NULL THEN
      RAISE EXCEPTION 'Exact item ID required for T1-T3';
    END IF;
    v_target_item_id := p_exact_item_id;
  ELSE
    IF p_category IS NULL THEN
      RAISE EXCEPTION 'Category required for T4-T5';
    END IF;
    -- Select random item
    SELECT id INTO v_target_item_id
    FROM items
    WHERE tier = p_tier 
      AND category = p_category 
      AND (is_gold_exclusive = FALSE OR is_gold_exclusive IS NULL)
    ORDER BY random()
    LIMIT 1;
    
    IF v_target_item_id IS NULL THEN
      RAISE EXCEPTION 'No items found for this category/tier';
    END IF;
  END IF;

  -- Get item name
  SELECT name INTO v_item_name FROM items WHERE id = v_target_item_id;

  -- Deduct fragments
  UPDATE user_profiles
  SET fragments = fragments - v_cost
  WHERE id = v_user_id;
  
  -- Add to inventory
  INSERT INTO user_inventory (user_id, item_id)
  VALUES (v_user_id, v_target_item_id)
  RETURNING id INTO v_new_instance_id;
  
  -- Log transaction
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'craft', 'fragments', -v_cost, 'Crafted ' || v_item_name);
  
  RETURN jsonb_build_object(
    'success', true, 
    'item_id', v_target_item_id, 
    'instance_id', v_new_instance_id,
    'name', v_item_name
  );
END;
$$;

-- 3. Buy Gold Pack
CREATE OR REPLACE FUNCTION buy_gold_pack(
  p_pack_id TEXT,
  p_amount_gold INT,
  p_cost_brl NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
BEGIN
  v_user_id := auth.uid();
  
  UPDATE user_profiles
  SET gold = COALESCE(gold, 0) + p_amount_gold
  WHERE id = v_user_id;
  
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'purchase', 'gold', p_amount_gold, 'Bought pack ' || p_pack_id);
  
  RETURN jsonb_build_object('success', true, 'new_gold', (SELECT gold FROM user_profiles WHERE id = v_user_id));
END;
$$;

-- 4. Buy Store Item (Latest version with purchases table)
CREATE OR REPLACE FUNCTION buy_store_item(
  p_item_id TEXT,
  p_cost_gold INT,
  p_type TEXT -- 'premium', 'codex', 'exclusive', 'boost'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_gold_owned INT;
  v_item_name TEXT;
  v_expires_at TIMESTAMP WITH TIME ZONE;
BEGIN
  v_user_id := auth.uid();
  
  SELECT gold INTO v_gold_owned FROM user_profiles WHERE id = v_user_id;
  
  IF v_gold_owned < p_cost_gold THEN
    RAISE EXCEPTION 'Insufficient gold';
  END IF;
  
  -- Deduct Gold
  UPDATE user_profiles
  SET gold = gold - p_cost_gold
  WHERE id = v_user_id;
  
  -- Calculate Expiration
  IF p_type = 'premium' THEN
    v_expires_at := NOW() + INTERVAL '30 days';
    v_item_name := 'Premium Membership';
    UPDATE user_profiles SET is_premium = TRUE WHERE id = v_user_id;
  ELSIF p_type = 'boost' THEN
    IF p_item_id = 'boost_xp_7d' THEN
        v_expires_at := NOW() + INTERVAL '7 days';
    ELSE
        v_expires_at := NOW() + INTERVAL '24 hours';
    END IF;
    v_item_name := 'XP Boost';
  ELSE
    v_expires_at := NULL; -- Permanent
    v_item_name := p_item_id;
  END IF;

  -- Record Purchase
  INSERT INTO user_purchases (user_id, product_type, product_id, gold_spent, expires_at, is_active)
  VALUES (v_user_id, p_type, p_item_id, p_cost_gold, v_expires_at, TRUE);

  -- Grant Item/Unlock Logic
  IF p_type = 'exclusive' THEN
    SELECT name INTO v_item_name FROM items WHERE id = p_item_id;
    INSERT INTO user_inventory (user_id, item_id) VALUES (v_user_id, p_item_id);
  ELSIF p_type = 'codex' THEN
    NULL; -- Client handles
  END IF;
  
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'spend', 'gold', -p_cost_gold, 'Bought ' || v_item_name);
  
  RETURN jsonb_build_object('success', true);
END;
$$;
