-- Create user_chests table
CREATE TABLE IF NOT EXISTS user_chests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
  chest_type VARCHAR(20) NOT NULL, -- 'incomum', 'ciclo', 'radiante', 'epico', 'season'
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  opened_at TIMESTAMP WITH TIME ZONE,
  is_opened BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_user_chests_user_opened ON user_chests (user_id, is_opened);

-- Create pity counters table
CREATE TABLE IF NOT EXISTS user_pity_counters (
  user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
  chest_type VARCHAR(20) NOT NULL,
  counter INT DEFAULT 0,
  last_reset TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (user_id, chest_type)
);

-- Procedure: Open Chest (by Type)
CREATE OR REPLACE FUNCTION open_chest(
  p_chest_type VARCHAR(20)
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_chest_id BIGINT;
  v_chest_type VARCHAR(20);
  v_pity_counter INT DEFAULT 0;
  v_guaranteed_tier INT DEFAULT 0;
  v_bonus_fragments INT;
  v_dropped_tier INT;
  v_dropped_item_id TEXT;
  v_is_duplicate BOOLEAN;
  v_recycle_value INT;
  v_fragments_gained INT DEFAULT 0;
  v_item_name TEXT;
  v_loot_table JSONB;
BEGIN
  v_user_id := auth.uid();
  v_chest_type := p_chest_type;
  
  -- 1. Verify chest ownership and status (Pick first available)
  SELECT id INTO v_chest_id
  FROM user_chests
  WHERE user_id = v_user_id AND chest_type = v_chest_type AND is_opened = FALSE
  LIMIT 1;
  
  IF v_chest_id IS NULL THEN
    RAISE EXCEPTION 'Chest not found or already opened';
  END IF;
  
  -- 2. Handle Pity System
  IF v_chest_type IN ('ciclo', 'radiante', 'epico', 'season') THEN
    SELECT COALESCE(counter, 0) INTO v_pity_counter 
    FROM user_pity_counters 
    WHERE user_id = v_user_id AND chest_type = v_chest_type;
    
    IF v_pity_counter IS NULL THEN
      INSERT INTO user_pity_counters (user_id, chest_type, counter) VALUES (v_user_id, v_chest_type, 0);
      v_pity_counter := 0;
    END IF;
    
    v_pity_counter := v_pity_counter + 1;
    
    -- Define guaranteed tier based on LOJA.MD
    v_guaranteed_tier := CASE 
      WHEN v_chest_type = 'ciclo' AND v_pity_counter >= 15 THEN 3
      WHEN v_chest_type = 'radiante' AND v_pity_counter >= 10 THEN 3
      WHEN v_chest_type = 'epico' AND v_pity_counter >= 8 THEN 4
      WHEN v_chest_type = 'season' AND v_pity_counter >= 5 THEN 5
      ELSE 0
    END;
  END IF;
  
  -- 3. Determine Drop Tier (Simplified Loot Logic)
  -- In a real scenario, we'd parse the JSON loot tables. Here we hardcode probabilities for simplicity and speed.
  DECLARE
    v_rand FLOAT := random() * 100;
  BEGIN
    IF v_guaranteed_tier > 0 THEN
      v_dropped_tier := v_guaranteed_tier; -- Force guaranteed tier (or better logic if needed)
      -- For simplicity, if guaranteed T3, we give T3.
    ELSE
      -- Basic Probabilities from LOJA.MD
      CASE v_chest_type
        WHEN 'incomum' THEN
          IF v_rand < 70 THEN v_dropped_tier := 1;
          ELSIF v_rand < 95 THEN v_dropped_tier := 2;
          ELSE v_dropped_tier := 3; END IF;
        WHEN 'ciclo' THEN
          IF v_rand < 40 THEN v_dropped_tier := 1;
          ELSIF v_rand < 75 THEN v_dropped_tier := 2;
          ELSIF v_rand < 95 THEN v_dropped_tier := 3;
          ELSE v_dropped_tier := 4; END IF;
        WHEN 'radiante' THEN
          IF v_rand < 45 THEN v_dropped_tier := 2;
          ELSIF v_rand < 85 THEN v_dropped_tier := 3;
          ELSIF v_rand < 95 THEN v_dropped_tier := 4;
          ELSE v_dropped_tier := 5; END IF;
        WHEN 'epico' THEN
          IF v_rand < 50 THEN v_dropped_tier := 3;
          ELSIF v_rand < 85 THEN v_dropped_tier := 4;
          ELSE v_dropped_tier := 5; END IF;
        WHEN 'season' THEN
          IF v_rand < 60 THEN v_dropped_tier := 4;
          ELSE v_dropped_tier := 5; END IF;
        ELSE
          v_dropped_tier := 1; -- Fallback
      END CASE;
    END IF;
  END;

  -- 4. Pick Item of Dropped Tier
  SELECT id, name, recycle_value INTO v_dropped_item_id, v_item_name, v_recycle_value
  FROM items
  WHERE tier = v_dropped_tier 
    AND (is_gold_exclusive = FALSE OR is_gold_exclusive IS NULL)
    AND (is_season_exclusive = (v_chest_type = 'season')) -- Prefer season items for season chest? Simplified logic.
  ORDER BY random()
  LIMIT 1;
  
  -- Fallback if no specific item found (e.g. season constraints)
  IF v_dropped_item_id IS NULL THEN
     SELECT id, name, recycle_value INTO v_dropped_item_id, v_item_name, v_recycle_value
     FROM items
     WHERE tier = v_dropped_tier LIMIT 1;
  END IF;

  -- 5. Check Duplicate
  SELECT EXISTS(SELECT 1 FROM user_inventory WHERE user_id = v_user_id AND item_id = v_dropped_item_id) INTO v_is_duplicate;
  
  IF v_is_duplicate THEN
    v_fragments_gained := v_recycle_value;
  ELSE
    INSERT INTO user_inventory (user_id, item_id) VALUES (v_user_id, v_dropped_item_id);
  END IF;
  
  -- 6. Bonus Fragments
  v_bonus_fragments := CASE v_chest_type
    WHEN 'incomum' THEN floor(random() * (15-5+1) + 5)
    WHEN 'ciclo' THEN floor(random() * (30-10+1) + 10)
    WHEN 'radiante' THEN floor(random() * (80-30+1) + 30)
    WHEN 'epico' THEN floor(random() * (200-80+1) + 80)
    WHEN 'season' THEN floor(random() * (500-200+1) + 200)
    ELSE 0
  END;
  
  v_fragments_gained := v_fragments_gained + v_bonus_fragments;
  
  UPDATE user_profiles 
  SET fragments = COALESCE(fragments, 0) + v_fragments_gained
  WHERE id = v_user_id;
  
  -- 7. Update Pity
  IF v_chest_type IN ('ciclo', 'radiante', 'epico', 'season') THEN
    IF v_dropped_tier >= v_guaranteed_tier AND v_guaranteed_tier > 0 THEN
       UPDATE user_pity_counters SET counter = 0, last_reset = NOW() WHERE user_id = v_user_id AND chest_type = v_chest_type;
    ELSE
       UPDATE user_pity_counters SET counter = v_pity_counter WHERE user_id = v_user_id AND chest_type = v_chest_type;
    END IF;
  END IF;
  
  -- 8. Close Chest
  UPDATE user_chests SET is_opened = TRUE, opened_at = NOW() WHERE id = v_chest_id;
  
  -- 9. Log
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'open_chest', 'fragments', v_fragments_gained, 'Opened ' || v_chest_type || ' chest. Got ' || v_item_name || (CASE WHEN v_is_duplicate THEN ' (Duplicate)' ELSE '' END));
  
  RETURN jsonb_build_object(
    'success', true,
    'item_id', v_dropped_item_id,
    'item_name', v_item_name,
    'tier', v_dropped_tier,
    'is_duplicate', v_is_duplicate,
    'fragments_gained', v_fragments_gained,
    'bonus_fragments', v_bonus_fragments
  );
END;
$$;

-- Helper to grant chest (for rewards)
CREATE OR REPLACE FUNCTION grant_chest(
  p_user_id UUID,
  p_chest_type TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO user_chests (user_id, chest_type) VALUES (p_user_id, p_chest_type);
END;
$$;
