CREATE TABLE IF NOT EXISTS user_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
  product_type VARCHAR(20) NOT NULL, -- 'premium', 'codex', 'boost', 'item_exclusive'
  product_id VARCHAR(50) NOT NULL,
  gold_spent INT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT TRUE,
  purchased_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_purchases_user_active ON user_purchases (user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_user_purchases_expires ON user_purchases (expires_at);

-- Update buy_store_item to use this table
CREATE OR REPLACE FUNCTION buy_store_item(
  p_item_id TEXT,
  p_cost_gold INT,
  p_type TEXT -- 'premium', 'codex', 'exclusive', 'boost'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_gold_owned INT;
  v_item_name TEXT;
  v_expires_at TIMESTAMP WITH TIME ZONE;
BEGIN
  v_user_id := auth.uid();
  
  SELECT gold INTO v_gold_owned FROM user_profiles WHERE id = v_user_id;
  
  IF v_gold_owned < p_cost_gold THEN
    RAISE EXCEPTION 'Insufficient gold';
  END IF;
  
  -- Deduct Gold
  UPDATE user_profiles
  SET gold = gold - p_cost_gold
  WHERE id = v_user_id;
  
  -- Calculate Expiration
  IF p_type = 'premium' THEN
    v_expires_at := NOW() + INTERVAL '30 days';
    v_item_name := 'Premium Membership';
    UPDATE user_profiles SET is_premium = TRUE WHERE id = v_user_id;
  ELSIF p_type = 'boost' THEN
    -- Check if it's 24h or 7d based on ID or look up
    IF p_item_id = 'boost_xp_7d' THEN
        v_expires_at := NOW() + INTERVAL '7 days';
    ELSE
        v_expires_at := NOW() + INTERVAL '24 hours';
    END IF;
    v_item_name := 'XP Boost';
  ELSE
    v_expires_at := NULL; -- Permanent
    v_item_name := p_item_id;
  END IF;

  -- Record Purchase
  INSERT INTO user_purchases (user_id, product_type, product_id, gold_spent, expires_at, is_active)
  VALUES (v_user_id, p_type, p_item_id, p_cost_gold, v_expires_at, TRUE);

  -- Grant Item/Unlock Logic
  IF p_type = 'exclusive' THEN
    SELECT name INTO v_item_name FROM items WHERE id = p_item_id;
    INSERT INTO user_inventory (user_id, item_id) VALUES (v_user_id, p_item_id);
  ELSIF p_type = 'codex' THEN
    -- We can't easily update the JSONB unlockedItems here without complex logic
    -- So we rely on the client to update the profile or use a separate table for unlocks
    -- Ideally we should have user_unlocks table.
    -- For now, we just log it.
    NULL; 
  END IF;
  
  INSERT INTO transactions (user_id, type, currency, amount, description)
  VALUES (v_user_id, 'spend', 'gold', -p_cost_gold, 'Bought ' || v_item_name);
  
  RETURN jsonb_build_object('success', true);
END;
$$;
