(() => {
  const D=window.MUNDO_DATA,$=s=>document.querySelector(s),host=$('#panel-host'),mapUI=$('#map-ui'),sceneUI=$('#scene-ui');
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths={leaf:'M19 4C7 2 3 8 5 15c7 5 15-1 14-11ZM5 20 15 9',people:'M16 21v-3c0-3-3-4-6-4s-6 1-6 4v3M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM17 4a3 3 0 0 1 0 6M19 14c2 1 3 2 3 5',bag:'M5 7h14l1 14H4L5 7ZM8 8V6a4 4 0 0 1 8 0v2',crown:'M3 7l4 4 5-7 5 7 4-4-3 12H6L3 7ZM7 22h10',sun:'M12 3V1M12 23v-2M3 12H1M23 12h-2M4 4l2 2M20 20l-2-2M4 20l2-2M20 4l-2 2M12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10Z',arrow:'M4 12h16M14 6l6 6-6 6',back:'M20 12H4M10 6l-6 6 6 6',chest:'M3 10c0-5 18-5 18 0v10H3V10ZM3 12h18M10 10v5h4v-5',x:'M6 6l12 12M18 6 6 18',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6Z',focus:'M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5M12 8v8M8 12h8',help:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM9 8a3 3 0 0 1 6 0c0 2-3 2-3 5M12 17v.1',check:'m5 12 4 4L19 6',build:'m4 20 7-7M8 4l4-2 9 9-3 3-9-9M3 21l-1-1 4-5 3 3-6 3Z',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12ZM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z'};
  function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"> <path d="${paths[name]||paths.leaf}"/></svg>`;}
  document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
  function art(kind='tree',theme='amber'){
    const palette=D.gardens.find(g=>g.id===theme)?.colors||['#bd835b','#d6ad7b'];
    let shape='';
    if(kind==='tree'||kind==='pine')shape=`<path d="M60 88Q52 59 64 31M57 61 38 41M59 54 83 36" stroke="#a68c62" stroke-width="5" fill="none"/>${[[38,37],[63,24],[84,36],[54,42],[72,43]].map(([x,y],i)=>`<ellipse cx="${x}" cy="${y}" rx="22" ry="14" fill="${kind==='pine'?['#637b57','#8da073'][i%2]:palette[i%2]}"/>`).join('')}`;
    if(kind==='stones')shape=`<path d="M23 65 31 43 51 38 66 58 58 80 35 82Z" fill="#9ba48d"/><path d="m59 73 11-24 26 2 13 24-18 13Z" fill="#c0c3a2"/><ellipse cx="47" cy="49" rx="15" ry="6" fill="#7b8d5d"/>`;
    if(kind==='lantern')shape='<path d="M55 86V53h10v33" fill="#8e9f82"/><ellipse cx="60" cy="88" rx="23" ry="5" fill="#a4ac8e"/><path d="M44 58V34h32v24Z" fill="#ecd091"/><path d="M32 35 60 17 88 35Z" fill="#8b9b7d"/><path d="M46 35v22M74 35v22" stroke="#697d68" stroke-width="4"/>';
    if(kind==='gate')shape='<path d="M31 90V36M88 90V36" stroke="#7e947c" stroke-width="7"/><path d="M18 25Q60 36 102 25M27 47h67" stroke="#ccb27b" stroke-width="5" fill="none"/>';
    if(kind==='water')shape='<ellipse cx="60" cy="58" rx="45" ry="25" fill="#6e9d93"/><path d="M24 53q36-18 72 0M27 65q33 12 64-1" stroke="#c0d0b0" stroke-width="2" fill="none"/>'+[[19,61],[39,79],[78,79],[102,60],[81,35],[38,35]].map(([x,y])=>`<ellipse cx="${x}" cy="${y}" rx="9" ry="6" fill="#acb69b"/>`).join('');
    return `<svg class="item-art" viewBox="0 0 120 104" aria-hidden="true"><ellipse cx="60" cy="87" rx="44" ry="9" fill="#0e2119" opacity=".35"/>${shape}</svg>`;
  }
  function gardenArt(g){return `<div class="garden-art ${g.id}">${art('tree',g.id)}<span>${g.theme}</span></div>`;}
  let current={type:'welcome'},stack=[],selection=null,engine,toastTimer;
  const favorites=new Set();
  $('#place-labels').innerHTML=D.places.map(p=>`<button class="place-label ${p.id==='garden'?'featured':''}" data-action="select" data-place="${p.id}" aria-label="Selecionar ${p.name}">${icon(p.icon)}<span>${p.name}</span></button>`).join('');
  try{engine=new window.MundoScene($('#stage'),{onSelect:selectPlace,onLayout:points=>points.forEach(p=>{const el=$(`[data-place="${p.id}"]`);if(el){el.style.left=p.x+'px';el.style.top=p.y+'px';}})});engine.show('hub');}
  catch(error){console.warn('Prévia gráfica indisponível:',error);$('#world-app').classList.add('no-webgl');$('#stage').innerHTML='<p class="scene-error">A prévia 3D precisa de WebGL. Os destinos e as interfaces continuam disponíveis abaixo.</p>';engine={show(){},setActive(){},select(){},zoom(){},reset(){},dispose(){}};}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
  function selectPlace(id){if(current.type!=='hub')return;selection=id;engine.select(id);D.places.forEach(p=>$(`[data-place="${p.id}"]`).classList.toggle('selected',p.id===id));const p=D.places.find(p=>p.id===id);if(!p)return;
    const dock=$('#destination-dock');dock.innerHTML=`<div class="dock-icon">${icon(p.icon)}</div><div><span class="eyebrow">${p.eyebrow}</span><h2>${p.name}</h2><p>${p.description}</p></div><button class="dock-enter" data-action="enter-place" data-place-id="${p.id}" aria-label="Entrar em ${p.name}">${icon('arrow')}</button><button class="dock-close" data-action="dismiss-selection" aria-label="Fechar seleção">${icon('x')}</button>`;dock.hidden=false;$('.map-footer').hidden=true;
  }
  function navigate(next){stack.push({...current});current=next;render();}
  function back(){current=stack.pop()||{type:'hub'};render();}
  function tabs(items,selected){return `<div class="tabs" role="tablist">${items.map(([id,label])=>`<button role="tab" aria-selected="${selected===id}" data-action="tab" data-tab="${id}">${label}</button>`).join('')}</div>`;}
  function panelFrame(title,eyebrow,body){return `<section class="panel" role="dialog" aria-modal="true" aria-label="${title}" tabindex="-1"><header class="panel-header"><button class="circle-button" data-action="back" aria-label="Voltar">${icon('back')}</button><div><p>${eyebrow}</p><h2>${title}</h2></div><span class="demo-badge">DEMO</span></header><div class="panel-body">${body}</div><footer class="panel-note">Conteúdo fictício · nada é enviado ou salvo</footer></section>`;}
  function panelGarden(){return panelFrame('Jardim do Silêncio','SEU AMBIENTE PESSOAL',`<div class="garden-hero">${gardenArt(D.gardens[0])}<span class="pill">Seu refúgio</span></div><div class="intro-copy"><p class="eyebrow">UM LUGAR PARA RESPIRAR</p><h3>O mundo lá fora.<br>O seu tempo aqui.</h3><p>Crie uma paisagem com a sua identidade ou entre apenas para contemplar.</p></div><div class="garden-actions"><button data-action="own-build">${icon('build')}<span><b>Construir</b><small>Prévia da entrada no editor</small></span>${icon('arrow')}</button><button data-action="own-explore">${icon('eye')}<span><b>Explorar</b><small>Prévia em primeira pessoa</small></span>${icon('arrow')}</button></div><button class="quiet-row" data-action="collection">${icon('chest')}<span>Coleção</span><small>Itens demonstrativos</small>${icon('arrow')}</button><p class="annotation">Estas entradas são simuladas. O Jardim funcional existente permanece separado e preservado.</p>`);}
  function panelShop(){const tab=current.tab||'Todas',items=D.items.filter(i=>tab==='Todas'||i.category===tab);return panelFrame('Loja','DETALHES QUE CRIAM LUGARES',`<div class="shop-banner"><span>${icon('leaf')}</span><div><p class="eyebrow">SELEÇÃO DO BOSQUE</p><h3>Beleza nos pequenos gestos.</h3><p>Uma coleção para imaginar seu jardim.</p></div></div>${tabs(['Todas','Natureza','Arquitetura','Atmosfera'].map(t=>[t,t]),tab)}<div class="item-grid">${items.map(i=>`<button class="item-card" data-action="item" data-id="${i.id}">${art(i.kind)}<small>${i.category}</small><b>${i.name}</b><span>Ver detalhe ${icon('arrow')}</span></button>`).join('')}</div><p class="annotation">Catálogo conceitual. Sem preços, moedas ou compras.</p>`);}
  function gardenCards(list){return list.map(g=>`<button class="garden-card" data-action="visit" data-id="${g.id}">${gardenArt(g)}<div><span>${g.owner} · jardim fictício</span><h4>${g.name}</h4><p>${g.description}</p><b>Visitar jardim ${icon('arrow')}</b></div></button>`).join('');}
  function panelSocial(){const tab=current.tab||'discover';let body='';
    if(tab==='discover')body=`<div class="intro-copy compact"><p class="eyebrow">OUTRAS FORMAS DE HABITAR</p><h3>Um encontro começa<br>com a curiosidade.</h3></div>${gardenCards(D.gardens)}`;
    if(tab==='friends')body=`<h3 class="section-title">Por perto</h3><p class="muted">Pessoas fictícias para testar este fluxo.</p><div class="people-list">${D.gardens.slice(0,2).map(g=>`<div class="person"><span class="avatar ${g.id}">${g.owner[0]}</span><div><b>${g.owner}</b><small>${g.name}</small></div><button data-action="visit" data-id="${g.id}">Ver jardim ${icon('arrow')}</button></div>`).join('')}</div>`;
    if(tab==='gardens')body=`<h3 class="section-title">Visitar jardins</h3><p class="muted">Três composições locais. Cada uma com seu próprio ritmo.</p>${gardenCards(D.gardens)}`;
    if(tab==='clan')body=`<div class="clan-crest">${icon('leaf')}<span>SEMENTES DO VALE</span><h3>Um mundo também<br>se faz em companhia.</h3><p>Clã demonstrativo · 4 membros</p></div><section class="collective-progress"><div><b>Presença coletiva</b><span>63% · exemplo</span></div><div class="progress-track"><span style="width:63%"></span></div><p>Um indicador visual de progresso do grupo, sem regras definidas neste experimento.</p></section><div class="section-heading"><h3>Membros</h3><span>4 pessoas fictícias</span></div><div class="people-list">${D.members.map(m=>`<div class="person"><span class="avatar">${m.initial}</span><div><b>${m.name}</b><small>${m.role}</small></div><span class="member-mark">${icon('leaf')}</span></div>`).join('')}</div><button class="primary full" data-action="clan-space">Visitar espaço do clã ${icon('arrow')}</button><p class="annotation">Sede, jardim comunitário ou santuário? O formato definitivo está em aberto. Esta visita mostra apenas uma possibilidade visual.</p>`;
    return panelFrame('Social','LUGARES PARA ESTAR EM COMPANHIA',tabs([['discover','Descobrir'],['friends','Amigos'],['gardens','Jardins'],['clan','Clã']],tab)+body);
  }
  function panelHall(){const tab=current.tab||'ranking';let body='';if(tab==='ranking')body=`<div class="hall-hero">${icon('crown')}<p class="eyebrow">GALERIA DE RECONHECIMENTO</p><h3>Pessoas que deixam marcas.</h3><p>Posições ilustrativas. Nenhum ranking real.</p></div><ol class="ranking-list">${D.ranking.map((p,i)=>`<li><span class="rank">${['I','II','III'][i]}</span><span class="avatar">${p.name[0]}</span><div><b>${p.name}</b><small>${p.garden}</small></div><span class="rank-label">${p.mark}</span></li>`).join('')}</ol>`;
    if(tab==='highlights')body=`<h3 class="section-title">Paisagens em destaque</h3><p class="muted">Uma curadoria fictícia de pequenos mundos.</p>${gardenCards([D.gardens[0],D.gardens[2]])}`;
    if(tab==='achievements')body=`<h3 class="section-title">Marcas de uma jornada</h3><div class="achievement-grid">${[['leaf','Paisagista'],['people','Em companhia'],['eye','Olhar atento']].map(([i,t])=>`<article>${icon(i)}<h4>${t}</h4><p>Conquista ilustrativa</p></article>`).join('')}</div><p class="annotation">Símbolos de reconhecimento sem critérios, desbloqueios ou recompensas reais.</p>`;
    return panelFrame('Hall da Fama','HISTÓRIAS QUE MERECEM SER VISTAS',tabs([['ranking','Ranking'],['highlights','Destaques'],['achievements','Conquistas']],tab)+body);
  }
  function panelSeason(){const tab=current.tab||'missions';let body='';if(tab==='missions')body=D.missions.map((m,i)=>`<details class="mission"><summary><span class="mission-icon">${icon(['leaf','eye','people'][i])}</span><span><b>${m.name}</b><small>${m.detail}</small></span><span>+</span></summary><p>Conteúdo demonstrativo para testar a leitura de um objetivo. Nenhuma ação é registrada.</p><div class="progress-track"><span style="width:${m.progress}%"></span></div><small>${m.text}</small></details>`).join('');
    if(tab==='events')body='<article class="event-card"><p class="eyebrow">EVENTO ILUSTRATIVO</p><h3>Encontros no bosque</h3><p>Um exemplo de espaço editorial para anunciar momentos da comunidade.</p><span class="pill">Sem data ou inscrição real</span></article>';
    if(tab==='rewards')body=`<div class="reward-example">${art('lantern')}<p class="eyebrow">RECOMPENSA CONCEITUAL</p><h3>Uma luz para o próximo capítulo.</h3><p>Apenas uma apresentação visual de recompensa. Não há resgate ou concessão de itens.</p><button class="secondary" data-action="item" data-id="lantern">Ver a lanterna</button></div>`;
    return panelFrame('Temporada','NOVOS HORIZONTES',`<div class="season-banner">${icon('sun')}<p class="eyebrow">CAPÍTULO DEMONSTRATIVO</p><h3>Estação das Folhas</h3><p>Pequenos convites para descobrir o Mundo.</p></div>${tabs([['missions','Missões'],['events','Eventos'],['rewards','Recompensas']],tab)}${body}`);
  }
  function panelCollection(){return panelFrame('Coleção','UM BAÚ DE POSSIBILIDADES',`<div class="intro-copy compact"><h3>Detalhes que contam<br>um pouco de você.</h3><p>Inventário fictício. Nenhum item foi comprado ou equipado.</p></div><div class="item-grid">${D.items.slice(0,4).map(i=>`<button class="item-card" data-action="item" data-id="${i.id}">${art(i.kind)}<small>Exemplo de item</small><b>${i.name}</b><span>Inspecionar ${icon('arrow')}</span></button>`).join('')}</div>`);}
  function panelItem(){const i=D.items.find(i=>i.id===current.id)||D.items[0];return panelFrame(i.name,'PRÉVIA DE ITEM',`<div class="item-hero">${art(i.kind)}</div><div class="intro-copy"><p class="eyebrow">${i.category.toUpperCase()}</p><h3>${i.name}</h3><p>${i.note}</p></div><button class="primary full" data-action="favorite" data-id="${i.id}">${icon(favorites.has(i.id)?'check':'star')}${favorites.has(i.id)?'Marcado nesta prévia':'Gostei desta ideia'}</button><p class="annotation">Marcação temporária, apenas para experimentar a interface. Sem compra, envio ou armazenamento.</p>`);}
  function panelHelp(){return panelFrame('Como navegar','UM MAPA SIMPLES',`<div class="intro-copy"><h3>Cinco lugares.<br>Um toque de distância.</h3><p>Toque em um destino no mapa ou em seu nome, depois use a seta Entrar. As funções abrem em interfaces 2D.</p><p>Arraste para deslocar um pouco a câmera. Os botões laterais aproximam, afastam ou centralizam o diorama.</p><p>No Social, explore os jardins fictícios ou abra Clã para visitar o espaço coletivo conceitual.</p><p>O jardim pessoal oferece entradas simuladas para Construir e Explorar. Nenhum protótipo existente é carregado ou alterado.</p><p>As animações param com as telas 2D abertas e respeitam a preferência de movimento reduzido do dispositivo.</p></div>`);}
  function sceneView(){const collective=current.type==='clanScene',g=D.gardens.find(g=>g.id===current.id)||D.gardens[0],own=!!current.own,explore=current.mode==='explore';
    return `<header class="visit-header"><button class="circle-button" data-action="back" aria-label="Voltar">${icon('back')}</button><div><p>${collective?'CLÃ SEMENTES DO VALE':own?'JARDIM PESSOAL · PRÉVIA':'VISITA DEMONSTRATIVA · '+g.owner.toUpperCase()}</p><h1>${collective?'Espaço coletivo':own?(explore?'Explorar · prévia':'Construir · prévia'):g.name}</h1></div></header><span class="visit-badge">${collective?'UMA POSSIBILIDADE EM ESTUDO':explore?'ARRASTE PARA OLHAR':'ARRASTE PARA OBSERVAR'}</span><div class="visit-footer"><p>${collective?'Uma identidade comum.<br>O formato ainda está em aberto.':own?'Uma entrada conceitual.<br>O editor original continua separado.':g.description}</p><div>${collective?`<button class="primary" data-action="back">Voltar ao clã ${icon('people')}</button>`:`<button class="primary" data-action="toggle-view">${icon(explore?'focus':'eye')}${explore?'Vista geral':'Ver de perto'}</button>${own?`<button class="secondary" data-action="collection">${icon('chest')}Coleção</button>`:''}`}</div></div>`;
  }
  function render(){
    const welcome=current.type==='welcome',hub=current.type==='hub',scene=current.type==='gardenScene'||current.type==='clanScene';
    $('#welcome').hidden=!welcome;mapUI.hidden=!(hub||welcome);mapUI.inert=!hub;sceneUI.hidden=!scene;sceneUI.inert=!scene;host.hidden=welcome||hub||scene;
    mapUI.setAttribute('aria-hidden',String(!hub));$('#stage').setAttribute('aria-hidden',String(!(hub||scene)));
    if(welcome){engine.setActive(true);$('#destination-dock').hidden=true;return;}
    if(hub){engine.show('hub');if(selection)selectPlace(selection);else{$('#destination-dock').hidden=true;$('.map-footer').hidden=false;}host.innerHTML='';sceneUI.innerHTML='';return;}
    if(scene){const kind=current.type==='clanScene'?'clan':'garden';engine.show(kind,current.id||'',current.mode||'overview');sceneUI.innerHTML=sceneView();host.innerHTML='';sceneUI.querySelector('button')?.focus({preventScroll:true});return;}
    engine.setActive(false);sceneUI.inert=true;mapUI.inert=true;
    const screens={garden:panelGarden,shop:panelShop,social:panelSocial,hall:panelHall,season:panelSeason,collection:panelCollection,item:panelItem,help:panelHelp};
    host.innerHTML=(screens[current.type]||panelHelp)();host.querySelector('.panel')?.focus({preventScroll:true});
  }
  $('#world-app').addEventListener('click',e=>{
    const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
    if(action==='start'){current={type:'hub'};render();toast('Escolha um lugar para começar.');}
    if(action==='select')selectPlace(button.dataset.place);
    if(action==='enter-place')navigate({type:button.dataset.placeId});
    if(action==='dismiss-selection'){selection=null;engine.select(null);$('#destination-dock').hidden=true;$('.map-footer').hidden=false;document.querySelectorAll('.place-label').forEach(el=>el.classList.remove('selected'));}
    if(action==='back')back();
    if(action==='zoom-in')engine.zoom(-.08);if(action==='zoom-out')engine.zoom(.08);if(action==='reset-camera')engine.reset();
    if(action==='help')navigate({type:'help'});if(action==='collection')navigate({type:'collection'});
    if(action==='tab'){current={...current,tab:button.dataset.tab};render();host.querySelector(`[data-tab="${button.dataset.tab}"]`)?.focus({preventScroll:true});}
    if(action==='item')navigate({type:'item',id:button.dataset.id});
    if(action==='favorite'){const id=button.dataset.id;if(favorites.has(id))favorites.delete(id);else favorites.add(id);render();toast(favorites.has(id)?'Ideia marcada somente nesta prévia.':'Marcação removida.');}
    if(action==='own-build')navigate({type:'gardenScene',id:'amber',own:true,mode:'overview'});
    if(action==='own-explore')navigate({type:'gardenScene',id:'amber',own:true,mode:'explore'});
    if(action==='visit')navigate({type:'gardenScene',id:button.dataset.id,mode:'overview'});
    if(action==='clan-space')navigate({type:'clanScene',mode:'overview'});
    if(action==='toggle-view'){current={...current,mode:current.mode==='explore'?'overview':'explore'};render();}
  });
  document.addEventListener('keydown',e=>{
    if(e.key==='Escape'&&current.type!=='welcome'&&current.type!=='hub'){e.preventDefault();back();}
    if(e.key==='Tab'&&!host.hidden){const focusable=[...host.querySelectorAll('button,a,input,summary,[tabindex="0"]')].filter(el=>!el.disabled);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===host.querySelector('.panel'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
  });
  window.addEventListener('pagehide',e=>{if(!e.persisted){clearTimeout(toastTimer);engine.dispose();}});
  render();
})();
