-- ACCOUNT DELETE EDGE SUPPORT
-- Run this in Supabase SQL Editor before deploying the account-delete Edge Function.

create table if not exists public.account_deletion_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  requested_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'started',
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists account_deletion_requests_user_id_idx
  on public.account_deletion_requests (user_id, requested_at desc);

alter table public.account_deletion_requests enable row level security;

revoke all on table public.account_deletion_requests from public;
revoke all on table public.account_deletion_requests from anon;
revoke all on table public.account_deletion_requests from authenticated;

create or replace function public._delete_public_rows_if_uuid_match(
  p_table_name text,
  p_column_name text,
  p_value uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_value is null then
    return;
  end if;

  if to_regclass(format('public.%I', p_table_name)) is null then
    return;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = p_table_name
      and column_name = p_column_name
  ) then
    execute format('delete from public.%I where %I = $1', p_table_name, p_column_name)
    using p_value;
  end if;
end;
$$;

create or replace function public._delete_public_rows_if_any_uuid_match(
  p_table_name text,
  p_column_names text[],
  p_value uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_where text;
begin
  if p_value is null then
    return;
  end if;

  if to_regclass(format('public.%I', p_table_name)) is null then
    return;
  end if;

  select string_agg(format('%I = $1', column_name), ' or ' order by ordinal_position)
  into v_where
  from information_schema.columns
  where table_schema = 'public'
    and table_name = p_table_name
    and column_name = any(p_column_names);

  if v_where is null then
    return;
  end if;

  execute format('delete from public.%I where %s', p_table_name, v_where)
  using p_value;
end;
$$;

create or replace function public._delete_public_rows_by_common_user_columns(p_value uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  table_row record;
begin
  if p_value is null then
    return;
  end if;

  for table_row in
    select
      table_name,
      array_agg(column_name order by ordinal_position)::text[] as column_names
    from information_schema.columns
    where table_schema = 'public'
      and column_name in (
        'user_id',
        'owner_id',
        'sender_id',
        'recipient_id',
        'mentor_id',
        'pupil_id',
        'friend_id'
      )
    group by table_name
  loop
    perform public._delete_public_rows_if_any_uuid_match(
      table_row.table_name,
      table_row.column_names,
      p_value
    );
  end loop;
end;
$$;

create or replace function public._nullify_public_uuid_column(
  p_table_name text,
  p_column_name text,
  p_value uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_value is null then
    return;
  end if;

  if to_regclass(format('public.%I', p_table_name)) is null then
    return;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = p_table_name
      and column_name = p_column_name
  ) then
    execute format('update public.%I set %I = null where %I = $1', p_table_name, p_column_name, p_column_name)
    using p_value;
  end if;
end;
$$;

create or replace function public.delete_account_data_for_user(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := p_user_id;
  v_leader_clan_id uuid;
begin
  if v_uid is null then
    return jsonb_build_object('success', false, 'error', 'EMPTY_USER_ID');
  end if;

  if to_regclass('public.clan_members') is not null then
    for v_leader_clan_id in
      select distinct clan_id
      from public.clan_members
      where user_id = v_uid
        and role = 'leader'
    loop
      perform public._delete_public_rows_if_uuid_match('clan_mission_participants', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_mission_progress', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_join_requests', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_aldeia_slots', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_aldeia_presence', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('sanctuary_positions', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('sanctuary_area_stats', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_members', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clans', 'id', v_leader_clan_id);
    end loop;
  end if;

  perform public._delete_public_rows_by_common_user_columns(v_uid);
  perform public._nullify_public_uuid_column('golden_invites', 'claimed_by_user_id', v_uid);
  perform public._delete_public_rows_if_uuid_match('user_profiles', 'id', v_uid);

  return jsonb_build_object('success', true);
exception
  when others then
    return jsonb_build_object('success', false, 'error', sqlerrm);
end;
$$;

revoke all on function public._delete_public_rows_if_uuid_match(text, text, uuid) from public;
revoke all on function public._delete_public_rows_if_any_uuid_match(text, text[], uuid) from public;
revoke all on function public._delete_public_rows_by_common_user_columns(uuid) from public;
revoke all on function public._nullify_public_uuid_column(text, text, uuid) from public;
revoke all on function public.delete_account_data_for_user(uuid) from public;

grant execute on function public.delete_account_data_for_user(uuid) to service_role;
