create table if not exists public.deleted_account_blocks (
  id bigint generated by default as identity primary key,
  email text not null,
  normalized_email text not null,
  deleted_user_id uuid,
  deleted_at timestamptz not null default now(),
  provider text,
  reason text,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists deleted_account_blocks_normalized_email_idx
  on public.deleted_account_blocks (normalized_email);

create index if not exists deleted_account_blocks_deleted_at_idx
  on public.deleted_account_blocks (deleted_at desc);

alter table public.deleted_account_blocks enable row level security;

revoke all on table public.deleted_account_blocks from public;
revoke all on table public.deleted_account_blocks from anon;
revoke all on table public.deleted_account_blocks from authenticated;

create or replace function public.register_deleted_account_block(
  p_email text,
  p_user_id uuid default null,
  p_provider text default null,
  p_reason text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := trim(coalesce(p_email, ''));
  v_normalized_email text := lower(v_email);
begin
  if v_normalized_email = '' then
    return jsonb_build_object('success', false, 'error', 'EMPTY_EMAIL');
  end if;

  insert into public.deleted_account_blocks (
    email,
    normalized_email,
    deleted_user_id,
    deleted_at,
    provider,
    reason,
    metadata
  )
  values (
    v_email,
    v_normalized_email,
    p_user_id,
    now(),
    nullif(trim(coalesce(p_provider, '')), ''),
    nullif(trim(coalesce(p_reason, '')), ''),
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (normalized_email) do update
  set email = excluded.email,
      deleted_user_id = excluded.deleted_user_id,
      deleted_at = excluded.deleted_at,
      provider = excluded.provider,
      reason = excluded.reason,
      metadata = coalesce(public.deleted_account_blocks.metadata, '{}'::jsonb) || coalesce(excluded.metadata, '{}'::jsonb);

  return jsonb_build_object('success', true);
end;
$$;

create or replace function public.get_deleted_account_block_status(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_block public.deleted_account_blocks%rowtype;
begin
  if v_email = '' then
    return jsonb_build_object('blocked', false);
  end if;

  select *
  into v_block
  from public.deleted_account_blocks
  where normalized_email = v_email
  limit 1;

  if not found then
    return jsonb_build_object('blocked', false);
  end if;

  return jsonb_build_object(
    'blocked', true,
    'email', v_block.email,
    'deleted_at', v_block.deleted_at,
    'reason', coalesce(v_block.reason, 'ACCOUNT_DELETED')
  );
end;
$$;

create or replace function public.release_golden_invite_claim_for_user(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.golden_invites%rowtype;
begin
  if p_user_id is null then
    return jsonb_build_object('success', false, 'error', 'EMPTY_USER_ID');
  end if;

  update public.golden_invites
  set is_used = false,
      claimed_by_user_id = null,
      claimed_at = null
  where claimed_by_user_id = p_user_id
    and is_used = true
  returning * into v_invite;

  return jsonb_build_object(
    'success', true,
    'released', found,
    'invite_code', v_invite.code
  );
end;
$$;

create or replace function public.delete_my_account_with_policy(
  p_block_reentry boolean default true,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_request_id bigint;
  v_leader_clan_id uuid;
  v_email text;
  v_provider text;
  v_block_result jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  end if;

  select email, coalesce(raw_app_meta_data->>'provider', app_metadata->>'provider')
  into v_email, v_provider
  from auth.users
  where id = v_uid;

  insert into public.account_deletion_requests (user_id, status, metadata)
  values (
    v_uid,
    'started',
    jsonb_build_object(
      'storage_cleanup_pending', true,
      'notes', 'SQL removed auth + database rows. Public storage files need separate cleanup if applicable.',
      'block_reentry', coalesce(p_block_reentry, true),
      'reason', p_reason
    )
  )
  returning id into v_request_id;

  if coalesce(p_block_reentry, true) and coalesce(trim(v_email), '') <> '' then
    select public.register_deleted_account_block(
      v_email,
      v_uid,
      v_provider,
      coalesce(nullif(trim(p_reason), ''), 'user_requested_account_deletion'),
      jsonb_build_object(
        'source', 'delete_my_account_with_policy',
        'request_id', v_request_id
      )
    )
    into v_block_result;

    if coalesce((v_block_result->>'success')::boolean, false) = false then
      raise exception '%', coalesce(v_block_result->>'error', 'FAILED_TO_REGISTER_DELETED_ACCOUNT_BLOCK');
    end if;
  elsif not coalesce(p_block_reentry, true) then
    select public.release_golden_invite_claim_for_user(v_uid)
    into v_block_result;

    if coalesce((v_block_result->>'success')::boolean, false) = false then
      raise exception '%', coalesce(v_block_result->>'error', 'FAILED_TO_RELEASE_GOLDEN_INVITE');
    end if;
  end if;

  if to_regclass('public.clan_members') is not null then
    for v_leader_clan_id in
      select distinct clan_id
      from public.clan_members
      where user_id = v_uid
        and role = 'leader'
    loop
      perform public._delete_public_rows_if_uuid_match('clan_mission_participants', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_mission_progress', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_join_requests', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_aldeia_slots', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_aldeia_presence', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('sanctuary_positions', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('sanctuary_area_stats', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clan_members', 'clan_id', v_leader_clan_id);
      perform public._delete_public_rows_if_uuid_match('clans', 'id', v_leader_clan_id);
    end loop;
  end if;

  perform public._delete_public_rows_by_common_user_columns(v_uid);
  perform public._nullify_public_uuid_column('golden_invites', 'claimed_by_user_id', v_uid);
  perform public._delete_public_rows_if_uuid_match('user_profiles', 'id', v_uid);

  delete from auth.users
  where id = v_uid;

  update public.account_deletion_requests
  set status = 'completed',
      completed_at = now(),
      metadata = metadata || jsonb_build_object(
        'completed_via', 'delete_my_account_with_policy',
        'block_reentry', coalesce(p_block_reentry, true),
        'reason', p_reason
      )
  where id = v_request_id;

  return jsonb_build_object('success', true);
exception
  when others then
    if v_request_id is not null then
      update public.account_deletion_requests
      set status = 'failed',
          completed_at = now(),
          metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
            'error', sqlerrm,
            'block_reentry', coalesce(p_block_reentry, true),
            'reason', p_reason
          )
      where id = v_request_id;
    end if;

    return jsonb_build_object('success', false, 'error', sqlerrm);
end;
$$;

create or replace function public.delete_my_account()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.delete_my_account_with_policy(true, null);
end;
$$;

create or replace function public.get_closed_beta_access_status()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_has_profile boolean := false;
  v_has_invite boolean := false;
  v_email text := '';
  v_reentry_blocked boolean := false;
  v_block_reason text := null;
begin
  if v_uid is null then
    return jsonb_build_object(
      'authorized', false,
      'has_profile', false,
      'has_invite', false,
      'reentry_blocked', false,
      'blocked_reason', null
    );
  end if;

  select exists(
    select 1
    from public.user_profiles
    where id = v_uid
  ) into v_has_profile;

  select exists(
    select 1
    from public.golden_invites
    where claimed_by_user_id = v_uid
      and is_used = true
  ) into v_has_invite;

  select lower(trim(coalesce(email, '')))
  into v_email
  from auth.users
  where id = v_uid;

  if coalesce(v_email, '') <> '' then
    select true, coalesce(reason, 'ACCOUNT_DELETED')
    into v_reentry_blocked, v_block_reason
    from public.deleted_account_blocks
    where normalized_email = v_email
    limit 1;
  end if;

  return jsonb_build_object(
    'authorized', (v_has_profile or v_has_invite) and not v_reentry_blocked,
    'has_profile', v_has_profile,
    'has_invite', v_has_invite,
    'reentry_blocked', v_reentry_blocked,
    'blocked_reason', v_block_reason
  );
end;
$$;

revoke all on function public.register_deleted_account_block(text, uuid, text, text, jsonb) from public;
revoke all on function public.get_deleted_account_block_status(text) from public;
revoke all on function public.release_golden_invite_claim_for_user(uuid) from public;
revoke all on function public.delete_my_account_with_policy(boolean, text) from public;
revoke all on function public.delete_my_account() from public;
revoke all on function public.get_closed_beta_access_status() from public;

grant execute on function public.register_deleted_account_block(text, uuid, text, text, jsonb) to service_role;
grant execute on function public.get_deleted_account_block_status(text) to anon;
grant execute on function public.get_deleted_account_block_status(text) to authenticated;
grant execute on function public.release_golden_invite_claim_for_user(uuid) to service_role;
grant execute on function public.release_golden_invite_claim_for_user(uuid) to authenticated;
grant execute on function public.delete_my_account_with_policy(boolean, text) to authenticated;
grant execute on function public.delete_my_account() to authenticated;
grant execute on function public.get_closed_beta_access_status() to authenticated;
