-- Deprecated on 2026-03-15.
-- The closed beta hold-state must happen after Google auth succeeds,
-- not by blocking user_profiles inserts during signup.
--
-- Use this file instead:
--   sql/fix_closed_beta_google_hold_state.sql
